export const S = {
  card: {
    background: "var(--color-background-primary)",
    border: "0.5px solid var(--color-border-tertiary)",
    borderRadius: 12,
    padding: "1rem 1.25rem",
  },
  input: {
    padding: "9px 12px",
    border: "0.5px solid var(--color-border-secondary)",
    borderRadius: 8,
    fontSize: 14,
    background: "var(--color-background-secondary)",
    color: "var(--color-text-primary)",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    transition: "border-color 0.15s",
  },
  label: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-text-secondary)",
    display: "block",
    marginBottom: 6,
  },
  muted: { color: "var(--color-text-secondary)" },
  badge: {
    income:  { background: "#DCFCE7", color: "#166534" },
    expense: { background: "#FEE2E2", color: "#991B1B" },
  },
  btn: {
    primary: {
      padding: "10px 18px",
      background: "var(--color-text-primary)",
      color: "var(--color-background-primary)",
      border: "none",
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 500,
      cursor: "pointer",
      fontFamily: "var(--font-sans)",
      transition: "opacity 0.15s",
    },
    ghost: {
      padding: "10px 18px",
      background: "transparent",
      color: "var(--color-text-secondary)",
      border: "0.5px solid var(--color-border-secondary)",
      borderRadius: 8,
      fontSize: 14,
      cursor: "pointer",
      fontFamily: "var(--font-sans)",
      transition: "background 0.15s",
    },
    danger: {
      padding: "4px 10px",
      background: "transparent",
      color: "#DC2626",
      border: "none",
      borderRadius: 6,
      fontSize: 12,
      cursor: "pointer",
      fontFamily: "var(--font-sans)",
    },
    edit: {
      padding: "4px 10px",
      background: "transparent",
      color: "var(--color-text-secondary)",
      border: "none",
      borderRadius: 6,
      fontSize: 12,
      cursor: "pointer",
      fontFamily: "var(--font-sans)",
    },
  },
};
